### ISSUE TITLE
Expand YAML comments to generate HTML documentation

### ISSUE THREAD

**Issue by codephi** [lowcarboncode/phlow#12]
YAML comments should support a Markdown structure to enable automatic HTML documentation generation.

In addition to serving the documentation locally using phlow docs, it should also be possible to export it using:
`phlow docs --export`

## Documentation Comment Format

Documentation comments must begin with `#!`.

```yaml
#! # Test Module
#! This module is an example of using Markdown documentation inside a Phlow file.
```

When placed directly before a parameter in `phlow.yaml`, the documentation will be displayed as an additional description alongside the parameter.

### Example:
```yaml
with:
  #! This parameter allows additional arguments to be injected if needed.
  additional_args:
    type: boolean
    description: If enabled, does not validate unmapped arguments.
    default: false
    required: false
```
### Rendered Markdown Output:
```markdown
## additional_args

This parameter allows additional arguments to be injected if needed.

| Type   | Description                                     | Default | Required |
|--------|-------------------------------------------------|---------|----------|
| boolean | If enabled, does not validate unmapped arguments. | false   | false     |
```
